### PR TITLE
Add configuration 'editor.showChangesInGutter'

### PR DESCRIPTION
**Pull request by FabianLauer**
This commit introduces the configuration `editor.showChangesInGutter`.

See https://github.com/Microsoft/vscode/issues/21795#issuecomment-308815360

### CODE REVIEW

**Comment by jens1o** [comment]
woah... Thanks! LGTM.

**Comment by FabianLauer** [comment]
Liked your changes a lot BTW, they worked out of the box. Without the ability to compile, that's really awesome 😮 👍

**Comment by jens1o** [comment]
I got used to it. :/

Will have to talk about this with my parents. The build isn't completed after 15 minutes :/

**Comment by FabianLauer** [comment]
Feel free to change my stuff if you want to!   :-)

**Comment by jens1o** [comment]
I'm fine with it. I'm going to create a pr, if you don't have something to interrupt.

**Comment by FabianLauer** [comment]
Nope, go right ahead.

**Pull request merged**
